services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - "6379:6379"
      - "8001:8001"
    environment:
      - REDIS_ARGS="--requirepass mypassword"ls

  api-gateway:
    build: ./api-gateway/
    container_name: api-gateway
    ports:
      - "3000:3000"
    volumes:
      - ./api-gateway/:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - CHOKIDAR_USEPOLLING=true

  upload-service:
    build: ./upload-service
    container_name: upload-service
    ports:
      - "3001:3001"
    volumes:
      - ./upload-service/:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=mypassword
    depends_on:
      - redis
